apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
